export const allUsersData = [
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 1
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 2

    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 3
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 4
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 5
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 6
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 7
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 8
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 9
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 10
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 11
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 12
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 13
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 14
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 15
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 16
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 17
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 18
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 19
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 20
        
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 21
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 22
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 23
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 24
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 25
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 26
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 27
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 28
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 29
    },
    {
        userName: 'Samantha Williams',
        userId: 'ID 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'Nigeria',
        phoneNumber: '23407058882017',
        hasBalance: false,
        emailVerified: true,
        referralJoin: false,
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 30
    },
]