export const transdata = [
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 1
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'NGN',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 2
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 3
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 4
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 5
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 6
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 7
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 8
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 9
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 10
    },
    {
        userName: 'Samantha Williams',
        userId: 'trx 123456789',
        totalBalance: 'NGN 15,000.00',
        currency: 'USD',
        DR: 'DR',
        phoneNumber: '23407058882017',
        date: new Date().toDateString(),
        role: 'anyRole',
        status: 'anyStatus',
        id: 11
    },
]